name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Unit tests
    runs-on: ubuntu-latest
    container: shellspec/shellspec
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shell test
        run: shellspec
        shell: bash
