name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ShellSpec and Run Tests
        run: |
          curl -fsSL https://git.io/shellspec | sh -s -- 0.28.1 --yes
          export PATH=$HOME/.local/bin:$PATH
          shellspec
        shell: bash

      - name: Action test
        uses: ./
        with:
          who-to-greet: "World"
