name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellSpec
        run: echo "y" | curl -fsSL https://git.io/shellspec | sh
        shell: bash

      - name: Shell test
        run: shellspec
        shell: bash
